version: '3'
services:
  tscript_ws:
    build: .
    command: bash -c "gunicorn -c gunicorn_conf.py tscript_ws:ts_flask_app"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/tscript_ws
    ports:
      - "8008:8008"
  # FOR CELERY MIGRATION IN THE FUTURE
  # depends_on:
  #   - redis
  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - 6379:6379
